### ISSUE TITLE
Legal Eevee/Eeveelutions do not pass the legality check

### ISSUE THREAD

**Issue by Majiya** [kwsch/PKHeX#1188]
It states relearn moves should all be set as (none) when they shouldn't be.
(Eevee shown is from a non-modded clean save - I checked several Eevees and a Sylveon, all legal, and all didn't pass the check for the same reason.)

https://puu.sh/w9PqZ/9fe7a48639.png
https://puu.sh/w9Prk/72ac609efe.png

**Comment by kwsch** [comment]
Was fixed shortly after the last release ([2 commits](https://github.com/kwsch/PKHeX/commit/92ca1e226361b5c910f8ab7b0b83b37c93b5d38c), day after).

Works fine on the latest commits :)

**Comment by Majiya** [comment]
Thanks for the fast response

I downloaded the latest (I thought) PKHeX today from the forum, is there a more recent download link on GitHub?

I can't find anything that includes the .exe

Thank you!

On 3 Jun 2017, at 20:14, Kurt <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1188<https://github.com/kwsch/PKHeX/issues/1188>.

**Comment by kwsch** [comment]
PKHeX uses TeamCity for continuous integration, the latest commits can be [accessed here](https://teamcity.projectpokemon.org/viewLog.html?buildTypeId=PKHeX_BuildWindows&buildId=lastSuccessful&buildBranch=%3Cdefault%3E) under the artifacts tab.

The forum download link is only updated when the current state is deemed stable enough for general release; the bleeding edge builds are not advertised 😈

**Comment by Majiya** [comment]
I never knew about the teamcity site.
Thanks for all your help, I appreciate it.


On 3 Jun 2017, at 20:32, Kurt <notifications@github.com<mailto:notifications@github.com>> wrote:


PKHeX uses TeamCity for continuous integration, the latest commits can be accessed here<https://teamcity.projectpokemon.org/viewLog.html?buildTypeId=PKHeX_BuildWindows&buildId=lastSuccessful&buildBranch=%3Cdefault%3E> under the artifacts tab.

The forum download link is only updated when the current state is deemed stable enough for general release; the bleeding edge builds are not advertised 😈

**Comment by InFeX90** [comment]
I checked according to the messages wrote above; still happening; the bug about eeveelutions... In anycase, also it's happening if the HO is chosen from the program, or if a legal breed came with HO already... legally I mean...
