### ISSUE TITLE
Character missing

### ISSUE THREAD

**Issue by Marctastikk** [kwsch/PKHeX#474]
I have the latest release and I edited my in game money, but now, in game,  my character is missing and the screen is frozen.

**Comment by kwsch** [comment]
Use the latest commit, this was fixed shortly after the last release.
Next release is sometime in the next 48h, have to let the latest features get tested before public release.

**Comment by Marctastikk** [comment]
What do you mean by the latest commit?

**Comment by kwsch** [comment]
http://teamcity.skyeditor.org/viewLog.html?buildId=4001&buildTypeId=PKHeX_PKHeXBuildPr&tab=artifacts

**Comment by Marctastikk** [comment]
I just tried re-doing the save on that build and im still having the same issue =[

**Comment by kwsch** [comment]
Use a backup not the glitched save. You can always enter in new coordinates
too. One of the recently closed issues has a screenshot of valid
coordinates.

**Comment by Marctastikk** [comment]
I dont have a backup :( could you link the closed issue with the screenie of the coordinates? Ill try that and pray it will work.

**Comment by Marctastikk** [comment]
Found the closed article. Gonna try it.

**Comment by Marctastikk** [comment]
Holy!! It worked. Thank you for the help. I appreciate your responses at this late hour.
